### ISSUE TITLE
train w/ FSDP OOM

### ISSUE THREAD

**Issue by Carlyx** [Lightricks/LTX-2#34]
Hi, amazing work!

When training with a 4-H100 FSDP setup (full fine-tuning), I encountered OOM during text_encoder loading stage.
 
This is likely because FSDP loads the entire model on the primary GPU (rank 0) by default before distributing it to all GPUs. 
However, the text_encoder is large, and the 4-GPU setup requires a large buffer, leading to an OOM on the rank0 GPU.

BTW,  If using a 2-H100 FSDP setup, the model can be loaded successfully,  but with OOM during `self._accelerator.prepare(self._transformer)`.

**Comment by hannalaguilar** [comment]
> Hi, amazing work!
> 
> When training with a 4-H100 FSDP setup (full fine-tuning), I encountered OOM during text_encoder loading stage.
> 
> This is likely because FSDP loads the entire model on the primary GPU (rank 0) by default before distributing it to all GPUs. However, the text_encoder is large, and the 4-GPU setup requires a large buffer, leading to an OOM on the rank0 GPU.
> 
> BTW, If using a 2-H100 FSDP setup, the model can be loaded successfully, but with OOM during `self._accelerator.prepare(self._transformer)`.

Same here but I'm trying LoRA config. Any solution?

**Comment by jiaxiangc** [comment]
same +1. The training scripts does not support mutl-gpus.

**Comment by rex-29** [comment]
Change the "_load_text_encoder_and_cache_embeddings" in LTX-2/packages/ltx-trainer/src/ltx_trainer/trainer.py

```
def _load_text_encoder_and_cache_embeddings(self) -> list[CachedPromptEmbeddings] | None:
        """Load text encoder, computes and returns validation embeddings."""

        # This method:
        #   1. Loads the text encoder on GPU
        #   2. If validation prompts are configured, computes and caches their embeddings
        #   3. Unloads the heavy Gemma model while keeping the lightweight embedding connectors
        #   The text encoder is kept (as self._text_encoder) but with model/tokenizer/feature_extractor
        #   set to None. Only the embedding connectors remain for use during training.
        local_rank = int(os.environ.get("LOCAL_RANK", 0))
        device = f"cuda:{local_rank}"
        # Load text encoder on GPU
        logger.debug("Loading text encoder...")
        if self._config.acceleration.load_text_encoder_in_8bit:
            logger.warning(
                "⚠️  load_text_encoder_in_8bit is set to True but 8-bit text encoder loading "
                "is not currently implemented. The text encoder will be loaded in bfloat16 precision."
            )
        self._text_encoder = load_text_encoder(
            checkpoint_path=self._config.model.model_path,
            gemma_model_path=self._config.model.text_encoder_path,
            device=device,
            dtype=torch.bfloat16,
        )

        # Cache validation embeddings if prompts are configured
        cached_embeddings = None
        if self._config.validation.prompts:
            logger.info(f"Pre-computing embeddings for {len(self._config.validation.prompts)} validation prompts...")
            cached_embeddings = []
            with torch.inference_mode():
                for prompt in self._config.validation.prompts:
                    v_ctx_pos, a_ctx_pos, _ = self._text_encoder(prompt)
                    v_ctx_neg, a_ctx_neg, _ = self._text_encoder(self._config.validation.negative_prompt)

                    cached_embeddings.append(
                        CachedPromptEmbeddings(
                            video_context_positive=v_ctx_pos.cpu(),
                            audio_context_positive=a_ctx_pos.cpu(),
                            video_context_negative=v_ctx_neg.cpu() if v_ctx_neg is not None else None,
                            audio_context_negative=a_ctx_neg.cpu() if a_ctx_neg is not None else None,
                        )
                    )

        # Unload heavy components to free VRAM, keeping only the embedding connectors
        self._text_encoder.model = None
        self._text_encoder.tokenizer = None
        self._text_encoder.feature_extractor_linear = None
        torch.cuda.empty_cache()

        logger.debug("Validation prompt embeddings cached. Gemma model unloaded")
        return cached_embeddings
```
works for me.

**Comment by zhangn77** [comment]
> Change the "_load_text_encoder_and_cache_embeddings" in LTX-2/packages/ltx-trainer/src/ltx_trainer/trainer.py
> 
> ```
> def _load_text_encoder_and_cache_embeddings(self) -> list[CachedPromptEmbeddings] | None:
>         """Load text encoder, computes and returns validation embeddings."""
> 
>         # This method:
>         #   1. Loads the text encoder on GPU
>         #   2. If validation prompts are configured, computes and caches their embeddings
>         #   3. Unloads the heavy Gemma model while keeping the lightweight embedding connectors
>         #   The text encoder is kept (as self._text_encoder) but with model/tokenizer/feature_extractor
>         #   set to None. Only the embedding connectors remain for use during training.
>         local_rank = int(os.environ.get("LOCAL_RANK", 0))
>         device = f"cuda:{local_rank}"
>         # Load text encoder on GPU
>         logger.debug("Loading text encoder...")
>         if self._config.acceleration.load_text_encoder_in_8bit:
>             logger.warning(
>                 "⚠️  load_text_encoder_in_8bit is set to True but 8-bit text encoder loading "
>                 "is not currently implemented. The text encoder will be loaded in bfloat16 precision."
>             )
>         self._text_encoder = load_text_encoder(
>             checkpoint_path=self._config.model.model_path,
>             gemma_model_path=self._config.model.text_encoder_path,
>             device=device,
>             dtype=torch.bfloat16,
>         )
> 
>         # Cache validation embeddings if prompts are configured
>         cached_embeddings = None
>         if self._config.validation.prompts:
>             logger.info(f"Pre-computing embeddings for {len(self._config.validation.prompts)} validation prompts...")
>             cached_embeddings = []
>             with torch.inference_mode():
>                 for prompt in self._config.validation.prompts:
>                     v_ctx_pos, a_ctx_pos, _ = self._text_encoder(prompt)
>                     v_ctx_neg, a_ctx_neg, _ = self._text_encoder(self._config.validation.negative_prompt)
> 
>                     cached_embeddings.append(
>                         CachedPromptEmbeddings(
>                             video_context_positive=v_ctx_pos.cpu(),
>                             audio_context_positive=a_ctx_pos.cpu(),
>                             video_context_negative=v_ctx_neg.cpu() if v_ctx_neg is not None else None,
>                             audio_context_negative=a_ctx_neg.cpu() if a_ctx_neg is not None else None,
>                         )
>                     )
> 
>         # Unload heavy components to free VRAM, keeping only the embedding connectors
>         self._text_encoder.model = None
>         self._text_encoder.tokenizer = None
>         self._text_encoder.feature_extractor_linear = None
>         torch.cuda.empty_cache()
> 
>         logger.debug("Validation prompt embeddings cached. Gemma model unloaded")
>         return cached_embeddings
> ```
> 
> works for me.

After using it still got:
DEBUG    [rank 0] 🎯 Using TextToVideoStrategy training strategy  __init__.py:57
         (audio enabled 🔈)                                                     
DEBUG    [rank 0] Loading text encoder...                         trainer.py:398
`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]
Loading checkpoint shards:  80%|████████  | 4/5 [00:00<00:00, 39.00it/s]
Loading checkpoint shards: 100%|██████████| 5/5 [00:00<00:00, 42.73it/s]
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
INFO     [rank 0] Pre-computing embeddings for 2 validation       trainer.py:414
         prompts...                                                             
DEBUG    [rank 0] Validation prompt embeddings cached. Gemma      trainer.py:436
         model unloaded                                                         
INFO     [rank 0] Loading LTX-2 model from                   model_loader.py:285
         /LTX-2/ltx-2-19b-                    
         dev.safetensors                                                        
DEBUG    [rank 0] Loading transformer...                     model_loader.py:290
DEBUG    [rank 0] Loading video VAE decoder...               model_loader.py:302
DEBUG    [rank 0] Loading audio VAE decoder...               model_loader.py:308
DEBUG    [rank 0] Loading vocoder...                         model_loader.py:314
INFO     [rank 0] MULTI_GPU distributed training enabled with 2   trainer.py:748
         processes                                                              
INFO     [rank 0] Local batch size: 1, global batch size: 2       trainer.py:755
DEBUG    [rank 0] Adding LoRA adapter with rank 32                trainer.py:521
DEBUG    [rank 0] Trainable params count: 213,909,504             trainer.py:512
W0113 09:22:05.506000 8833 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 8991 closing signal SIGTERM
E0113 09:22:05.771000 8833 torch/distributed/elastic/multiprocessing/api.py:882] failed (exitcode: -11) local_rank: 0 (pid: 8990) of binary
